### ISSUE TITLE
where is the “Global and local feature fusion”

### ISSUE THREAD

**Issue by Minsky520** [sydai/referring-expression-counting#4]
Hi, may I ask in which file of the code the “Global and local feature fusion” part mentioned in the paper is represented, I don't seem to find that part, looking forward to your reply.
![image](https://github.com/user-attachments/assets/d3bc1407-a4dc-4d48-aacc-8c074b7ee2ff)

**Comment by Kkkkkz21** [comment]
In the file path which is 'referring-expression-counting-main\GroundingDINO\groundingdino\models\GroundingDINO\transformer.py'.
![image](https://github.com/user-attachments/assets/fbed07c3-6f83-4189-af1e-b9ace20d34be)

**Comment by Minsky520** [comment]
> In the file path which is 'referring-expression-counting-main\GroundingDINO\groundingdino\models\GroundingDINO\transformer.py'. ![image](https://private-user-images.githubusercontent.com/166676756/356802229-fbed07c3-6f83-4189-af1e-b9ace20d34be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODA5OTUsIm5iZiI6MTcyMzg4MDY5NSwicGF0aCI6Ii8xNjY2NzY3NTYvMzU2ODAyMjI5LWZiZWQwN2MzLTZmODMtNDE4OS1hZjFlLWI5YWNlMjBkMzRiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwNzQ0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDliODFjMGNkYzA3NTE4ZTE4OThlMDVkYmUyYjRjOTYyYjkzOTY3NDIzYmM5NmYwMjExOWY2ODM0MjE4ZTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KHWoO5OQS5zzQPIebRn4kBYI-wST4pGnsIgAqjWg6Qg)

thank you for your help!!!
