### ISSUE TITLE
Replace DETRAC dataset download link

### ISSUE THREAD

**Issue by PREPONDERANCE** [sydai/referring-expression-counting#6]
This link provided in READEM will be redirected to the homepage of Albany Computer Vision and Machine Learning Lab. It took me fair enough time to finally download the dataset.

I'd like to replace the original link to [this link](https://wayback.archive-it.org/org-652/20231112212640/https://detrac-db.rit.albany.edu/download) to ease the download process.

**Comment by Daromog** [comment]
Hi, that link is not working, could you please share where to download?

**Comment by PREPONDERANCE** [comment]
Try this

https://wayback.archive-it.org/org-652/20231112212640/https://detrac-db.rit.albany.edu/download
