### ISSUE TITLE
Assertion Error When Training the Model

### ISSUE THREAD

**Issue by PREPONDERANCE** [sydai/referring-expression-counting#8]
```
Traceback (most recent call last):
  File "/Users/mac/Research/referring-expression-counting/train_test.py", line 423, in <module>
    ) = train(epoch)
        ^^^^^^^^^^^^
  File "/Users/mac/Research/referring-expression-counting/train_test.py", line 111, in train
    loss_dict = criterion(outputs, targets, mask_bi)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Research/referring-expression-counting/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Research/referring-expression-counting/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Research/referring-expression-counting/utils/criterion.py", line 315, in forward
    self.get_loss(
  File "/Users/mac/Research/referring-expression-counting/utils/criterion.py", line 296, in get_loss
    return loss_map[loss](outputs, targets, indices, num_points, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Research/referring-expression-counting/utils/criterion.py", line 200, in loss_contrast
    assert "img_embs" in outputs and "txt_embs" in outputs
                                     ^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

I ran the `train_test.py` file and the program threw the above assertion error. What could possibly lead to this?

**Comment by Minsky520** [comment]
> ```
> Traceback (most recent call last):
>   File "/Users/mac/Research/referring-expression-counting/train_test.py", line 423, in <module>
>     ) = train(epoch)
>         ^^^^^^^^^^^^
>   File "/Users/mac/Research/referring-expression-counting/train_test.py", line 111, in train
>     loss_dict = criterion(outputs, targets, mask_bi)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/mac/Research/referring-expression-counting/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/mac/Research/referring-expression-counting/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/mac/Research/referring-expression-counting/utils/criterion.py", line 315, in forward
>     self.get_loss(
>   File "/Users/mac/Research/referring-expression-counting/utils/criterion.py", line 296, in get_loss
>     return loss_map[loss](outputs, targets, indices, num_points, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/mac/Research/referring-expression-counting/utils/criterion.py", line 200, in loss_contrast
>     assert "img_embs" in outputs and "txt_embs" in outputs
>                                      ^^^^^^^^^^^^^^^^^^^^^
> AssertionError
> ```
> 
> I ran the file and the program threw the above assertion error. What could possibly lead to this?`train_test.py`

大佬你好，可以问一下这个text_threshold大小是多少吗，如何设置
![image](https://github.com/user-attachments/assets/9b39a727-0c43-4444-b707-b82701624556)

**Comment by PREPONDERANCE** [comment]
The problem is with the version of groundingdino package.

**Steps**:

1. Navigate to where GroundingDINO folder is.
2. `python -m setup install`
3. `pip install .`

This will install `groundingdino==0.1.0` in local env.

**Comment by PREPONDERANCE** [comment]
> The problem is with the version of groundingdino package.
> 
> **Steps**:
> 
> 1. Navigate to where GroundingDINO folder is.
> 2. `python -m setup install`
> 3. `pip install .`
> 
> This will install `groundingdino==0.1.0` in local env.

@sydai Would you consider putting this into README? It would be helpful for people unfamiliar with custom installation.
