### ISSUE TITLE
How to set text_threshold

### ISSUE THREAD

**Issue by Minsky520** [sydai/referring-expression-counting#9]
Hi author, what is the size of text_threshold in line 49 of referring-expression-counting-main/GroundingDINO/groundingdino/util/base.api.py?
![image](https://github.com/user-attachments/assets/a99cc0ec-7cc6-435f-9af0-e853c395477e)

**Comment by PREPONDERANCE** [comment]
Set to 0.5 for default value and finetune the value by the validation results.

**Comment by Minsky520** [comment]
> 将默认值设置为 0.5，并通过验证结果微调该值。
谢谢您的回复，我尽快去试试
